name: Deploy PR Preview to WinSrv

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get PR metadata
        id: meta
        run: |
          echo "user=$(jq -r .pull_request.user.login $GITHUB_EVENT_PATH)" >> $GITHUB_OUTPUT

      - name: Rsync Code to Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_UNAME }}
          password: ${{ secrets.SSH_SERVER_PWORD }}
          source: "."
          target: ${{ secrets.SSH_SERVER_PATH }}

      - name: Run Deployment Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_UNAME }}
          password: ${{ secrets.SSH_SERVER_PWORD }}
          script: |
            cd C:\${{ secrets.SSH_SERVER_PATH }}\${{ steps.meta.outputs.user }}
            npm install
            ./deploy-pr.ps1 ${{ steps.meta.outputs.user }}
